language: php
sudo: false
install: composer install

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - mkdir -p build/logs

after_success:
  - travis_retry php vendor/bin/php-coveralls
