<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Litipk\\BigNumbers\\' => array($vendorDir . '/litipk/php-bignumbers/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Dotenv\\' => array($vendorDir . '/vlucas/phpdotenv/src'),
    'B2Binpay\\Tests\\' => array($vendorDir . '/b2binpay/api-php/tests'),
    'B2Binpay\\' => array($vendorDir . '/b2binpay/api-php/src'),
);
